apiVersion: apps/v1
kind: Deployment
metadata:
  name: windriver-alert-schedular-deployment
  labels:
    app: windriver-alert-schedular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windriver-alert-schedular
  template:
    metadata:
      labels:
        app: windriver-alert-schedular
    spec:
      containers:
        - name: windriver-alert-schedular
          image: ispeck1/windriver-alertschedular:v1
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: database_host
              value: "127.0.0.1"
            - name: database_port
              value: "3306"
            - name: database_user
              value: "user"
            - name: database_pass
              value: "password"
            - name: database_schema
              value: "schema"
            - name: alert_interval
              value: "10"
            - name: transaction_table_name
              value: "event_transactions"
            - name: alert_table_name
              value: "alert"
            - name: event_category_table_name
              value: "event_category"
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
