apiVersion: apps/v1
kind: Deployment
metadata:
  name: windriver-people-count-deployment
  labels:
    app: windriver-people-count
spec:
  replicas: 1  # Number of replicas (Pods) you want to run
  selector:
    matchLabels:
      app: windriver-people-count
  template:
    metadata:
      labels:
        app: windriver-people-count
    spec:
      containers:
        - name: windriver-people-count
          image: ispeck1/windriver_pc:v1
          env:
            - name: RTSP_URL
              value: "your RTSP URL"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "user"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_SCHEMA
              value: "schema"
            - name: pipeline_id
              value: "608"
            - name: TABLE_CAM_MASTER
              value: "camera"
            - name: TABLE_CLASS_MASTER
              value: "class"
            - name: TABLE_MODEL_MASTER
              value: "model"
            - name: TABLE_OBJECT_INSIGHT
              value: "event_transactions"
            - name: TABLE_PIPELINE_MASTER
              value: "pipeline"
            - name: TABLE_PIPELINE_CLASS_MAP
              value: "pipeline_class_map"
            - name: INSIGHTS_UPDATE_MODE_TIME_INTERVAL
              value: "5"
            - name: SAVE_IMAGE
              value: "True"
            - name: SHOW_IMAGE
              value: "True"
            - name: DIRECTORY_SAVE_IMAGE
              value: "OUT"
            - name: SAVE_INSIGHT
              value: "True"
            - name: SKIP_FRAMES
              value: "2"
            - name: MODEL_WEIGHT
              value: "weights/yolov6m.pt"
            - name: MODEL_CLASS_YML
              value: "data/coco.yaml"
            - name: MODEL_ALERT_CLASS_LIST
              value: '["Person detected"]'
            - name: ROI
              value: "[]"
            - name: TIMEZONE_CONVERT
              value: "Asia/Singapore"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
            - mountPath: /engine/OUT
              name: image-output
          resources:
            limits:
              nvidia.com/gpu: 1  # Ensure GPU is allocated

      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: image-output
          hostPath:
            path: /esentinel/alert_images  # Fixed path like previous config
