apiVersion: apps/v1
kind: Deployment
metadata:
  name: windriver-ppe-detection-deployment
  labels:
    app: windriver-ppe-detection
spec:
  replicas: 1  # Uncomment to ensure a pod is created
  selector:
    matchLabels:
      app: windriver-ppe-detection
  template:
    metadata:
      labels:
        app: windriver-ppe-detection
    spec:
      containers:
        - name: windriver-ppe-detection
          image: ispeck1/windriver_ppe:v1
          env:
            - name: RTSP_URL
              value: "rtsp://admin:Secure369@165.21.14.98:554/Streaming/Channels/1401"
            - name: DB_HOST
              value: "43.230.202.167"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "ispeck"
            - name: DB_PASSWORD
              value: "Root#1234"
            - name: DB_SCHEMA
              value: "power_automation_mod"
            - name: pipeline_id
              value: "905"
            - name: TABLE_CAM_MASTER
              value: "camera"
            - name: TABLE_CLASS_MASTER
              value: "class"
            - name: TABLE_MODEL_MASTER
              value: "model"
            - name: TABLE_OBJECT_INSIGHT
              value: "event_transactions"
            - name: TABLE_PIPELINE_MASTER
              value: "pipeline"
            - name: TABLE_PIPELINE_CLASS_MAP
              value: "pipeline_class_map"
            - name: INSIGHTS_UPDATE_MODE_TIME_INTERVAL
              value: "5"
            - name: SAVE_IMAGE
              value: "True"
            - name: SHOW_IMAGE
              value: "True"
            - name: DIRECTORY_SAVE_IMAGE
              value: "OUT"
            - name: SAVE_INSIGHT
              value: "True"
            - name: SKIP_FRAMES
              value: "1"
            - name: MODEL_WEIGHT
              value: "weights/yolov6m.pt"
            - name: MODEL_CLASS_YML
              value: "data/coco.yaml"
            - name: ROI
              value: "[]"
            - name: TIMEZONE_CONVERT
              value: "Asia/Singapore"
          volumeMounts:
            - mountPath: /engine/OUT
              name: image-output
          resources:
            limits:
              nvidia.com/gpu: 1  # Ensure NVIDIA GPU is available

      volumes:
        - name: image-output
          hostPath:
            path: /esentinel/alert_images
