apiVersion: apps/v1
kind: Deployment
metadata:
  name: esentinel-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esentinel-client
  template:
    metadata:
      labels:
        app: esentinel-client
    spec:
      containers:
        - name: esentinel-client
          image: ispeck1/windriver_esentinel_frontend:v1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config-volume
          hostPath:
            path: path/to/nginx.conf
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: esentinel-client-service
spec:
  type: NodePort
  selector:
    app: esentinel-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
