apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-docker-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-docker-vm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:24.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              package_update: true
              package_upgrade: true
              users:
                - name: ubuntu
                  groups: sudo
                  shell: /bin/bash
                  lock_passwd: false  # Ensure password is not locked
                  passwd: "$6$gJ3DwG8z$ZVfZz3zViUnF/N2.2Wx8hbo6E6A1z9Jx/NJpjM3ct1oU.Y3M4Q0t3bX0MJsMiF1fMz/.lwKxOTGAaH3ZIueLw1"
              ssh_pwauth: true  # Enable SSH password authentication
              disable_root: false  # Allow root login (optional)
              runcmd:
                - apt-get update -y
                - apt-get install -y docker.io openssh-server
                - systemctl enable docker
                - systemctl enable ssh
                - systemctl start ssh

---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-docker-vm-service
spec:
  type: NodePort # Use NodePort to expose the service externally
  selector:
    kubevirt.io/domain: ubuntu-docker-vm # Match the VM's label
  ports:
    - name: ssh
      port: 22 # Port exposed by the Service
      targetPort: 22 # Port inside the VM
      nodePort: 30022 # Optional: Specify a NodePort for SSH (default range: 30000-32767)
    - name: http
      port: 80 # Port exposed by the Service
      targetPort: 80 # Port inside the VM
      nodePort: 30080 # Optional: Specify a NodePort for HTTP (default range: 30000-32767)
