version: "3.8"
services:
  orchestrator:
    image: ispeck1/esentinel_containerschedular:v2
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      PYTHONUNBUFFERED: 1
    volumes:
      - ./yamls:/yamls
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /etc/localtime:/etc/localtime:ro
      - ./scheduler.sqlite:scheduler.sqlite
    restart: always
